# Generated by Django 3.1 on 2024-03-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_auto_20240301_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
